version: '3.8'

services:
  database:
    container_name: DB
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: ${MYSQL_API_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql