INSERT INTO bpm_items (name, description)
VALUES ('BPMN 2.0', 'graphical notation based on flowcharting techniques'),
       ('Declarative', 'implicit annotation with constrains'),
       ('eGantt', 'extension of the Gantt Chart with an emphasis to capture time characteristics'),
       ('EPC', 'planning of implementation and configuration of resources in a enterprise setting'),
       ('Flow', 'Flowcharts as a easy to understand BPMN'),
       ('IDEF3',
        'modeling of processes with a focus on the process flow as well as the state of objects and respective conditions'),
       ('Petri Net', 'used for describing distributed systems and has a mathematical theory'),
       ('UML Act.', 'documents activity and control flow as a float chart');

INSERT INTO bpm_user (name)
VALUES ('Peter'),
       ('Hans'),
       ('Mike'),
       ('Max'),
       ('Günter'),
       ('Felix');

INSERT INTO bpm_user_recommendation (item_id, userid, rating)
VALUES (1, 1, 3),
       (2, 1, 1),
       (3, 1, 4),
       (4, 1, 2),
       (5, 1, 5),
       (6, 1, 1),
       (7, 1, 3),
       (8, 2, 3),
       (1, 2, 2),
       (4, 2, 3),
       (5, 2, 4),
       (6, 2, 2),
       (7, 2, 1),
       (8, 2, 1),
       (1, 3, 3),
       (2, 3, 1),
       (3, 3, 4),
       (4, 3, 2),
       (5, 3, 5),
       (6, 3, 1),
       (7, 3, 3),
       (8, 3, 3),
       (1, 4, 3),
       (2, 4, 1),
       (3, 4, 4),
       (4, 4, 2),
       (5, 4, 5),
       (6, 4, 1),
       (7, 4, 3),
       (8, 4, 3),
       (1, 5, 3),
       (2, 5, 1),
       (3, 5, 4),
       (4, 5, 2),
       (5, 5, 5),
       (6, 5, 1),
       (7, 5, 3),
       (8, 5, 3),
       (1, 6, 3),
       (2, 6, 1),
       (3, 6, 4),
       (4, 6, 2),
       (5, 6, 5),
       (6, 6, 1),
       (7, 6, 3),
       (8, 6, 3);