name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        working-directory: ./API/
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run project with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BPM_CONFIG: ${{ secrets.BPM_CONFIG }}
        working-directory: ./API/
        run: |
          ./gradlew --warning-mode all build --no-daemon
      - name: release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          files: "build/*-all.jar"
        env:
          GITHUB_TOKEN: ${{ github.token }}